name: Pipeline

on: [push, workflow_dispatch]

env:
  APPLICATION_NAME: Mascot

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      
      - name: Install requirements
        run: pip install --requirement development-requirements.txt

      - name: Lint code
        run: |
          flake8 --ignore=E501,E231 *.py
          pylint --disable=C0301 *.py
      
      - name: Run unit tests
        run: python -m unittest --verbose --failfast

  build:
    needs: lint-and-test
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      # Set up the docker build environment
      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Login to GitHub Container Registry
      # https://github.com/marketplace/actions/docker-login
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push container image with Buildx
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          tags: ${{ github.ref }}
          push: true
